<a href="https://colab.research.google.com/github/nika-va/practice/blob/main/tensorflow_fundamentas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* Introduction to tensors (creating tensors)
* Getting information from tensors (tensor attributes)
* Manipulating tensors (tensor operations)
* Tensors and NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow
* Exercises to try

In [2]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [3]:
a = tf.constant([[2,5,20]], dtype=tf.float32)

In [4]:
a.ndim

2

In [5]:
a

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 2.,  5., 20.]], dtype=float32)>

In [6]:
# scalar 0
# vector 1
# matrix 2
# tensor n+

In [7]:
# tensors with tf.Variable
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [8]:
changeable_tensor[0].assign(2)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([2, 7], dtype=int32)>

### Random Tensors

In [9]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal([2,3])
random_2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193765, -1.8107855 ]], dtype=float32)>

In [10]:
not_shuffled = tf.random.Generator.from_seed(7).normal([3,2])
not_shuffled


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.2878567 ],
       [-0.8757901 , -0.08857017],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [11]:
tf.random.set_seed(32)
tf.random.shuffle(not_shuffled, seed=3)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.8757901 , -0.08857017],
       [-1.3240396 ,  0.2878567 ],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [12]:

# Set the random seed
tf.random.set_seed(42)

# Generate some random numbers
a = tf.random.normal([1])
b = tf.random.normal([1])

# Check that the results are the same every time
print(a)
print(b)

tf.Tensor([0.3274685], shape=(1,), dtype=float32)
tf.Tensor([0.08422458], shape=(1,), dtype=float32)


In [13]:
tf.random.set_seed(42)
# Generate some random numbers with a specific seed
a = tf.random.normal([1])

# Check that the results are the same every time
print(a)


tf.Tensor([0.3274685], shape=(1,), dtype=float32)


In [14]:

b = tf.random.normal([1])
print(b)

tf.Tensor([0.08422458], shape=(1,), dtype=float32)


In [15]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal([4,5])
print(random_1)
tf.random.shuffle(random_1)

tf.Tensor(
[[-0.7565803  -0.06854702  0.07595026 -1.2573844  -0.23193765]
 [-1.8107855   0.09988727 -0.50998646 -0.7535806  -0.5716629 ]
 [ 0.1480774  -0.23362991 -0.3522796   0.40621266 -1.0523509 ]
 [ 1.2054597   1.6874489  -0.44629744 -2.3410842   0.99009085]], shape=(4, 5), dtype=float32)


<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193765],
       [ 1.2054597 ,  1.6874489 , -0.44629744, -2.3410842 ,  0.99009085],
       [-1.8107855 ,  0.09988727, -0.50998646, -0.7535806 , -0.5716629 ],
       [ 0.1480774 , -0.23362991, -0.3522796 ,  0.40621266, -1.0523509 ]],
      dtype=float32)>

In [16]:
tf.ones([10,7])
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [17]:
import numpy as np
np.ones([10,7])

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [18]:
numpy = np.arange(1,25)
numpy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [19]:
tf.constant(numpy, shape = (2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [20]:
a = np.arange(1,61, dtype=np.int32)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60], dtype=int32)

In [21]:
b = tf.constant(a, shape=(5,6,2))
b

<tf.Tensor: shape=(5, 6, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18],
        [19, 20],
        [21, 22],
        [23, 24]],

       [[25, 26],
        [27, 28],
        [29, 30],
        [31, 32],
        [33, 34],
        [35, 36]],

       [[37, 38],
        [39, 40],
        [41, 42],
        [43, 44],
        [45, 46],
        [47, 48]],

       [[49, 50],
        [51, 52],
        [53, 54],
        [55, 56],
        [57, 58],
        [59, 60]]], dtype=int32)>

In [22]:
a.shape


(60,)

In [23]:
b[0, :2]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [24]:
tensor = tf.random.uniform((2,4,3), minval=2, maxval=12, dtype=tf.int64)
tensor

<tf.Tensor: shape=(2, 4, 3), dtype=int64, numpy=
array([[[ 6, 10,  4],
        [ 6,  2,  3],
        [ 3,  5,  6],
        [ 9,  8, 10]],

       [[ 2, 10, 11],
        [ 3,  2,  9],
        [ 7,  7,  2],
        [ 3,  3,  4]]])>

In [25]:
tensor[:, -1]

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[ 9,  8, 10],
       [ 3,  3,  4]])>

In [26]:
# Adding extra dimention to our rank 2 tensor
tensor = tensor[:, tf.newaxis, :]
tensor

<tf.Tensor: shape=(2, 1, 4, 3), dtype=int64, numpy=
array([[[[ 6, 10,  4],
         [ 6,  2,  3],
         [ 3,  5,  6],
         [ 9,  8, 10]]],


       [[[ 2, 10, 11],
         [ 3,  2,  9],
         [ 7,  7,  2],
         [ 3,  3,  4]]]])>

In [27]:
# a = tf.expand_dims(tensor, axis=-1)
# a = tf.tile(a, multiples=[2,2,2,2])
# a.shape

In [28]:
tf.expand_dims(tensor, axis=0)

<tf.Tensor: shape=(1, 2, 1, 4, 3), dtype=int64, numpy=
array([[[[[ 6, 10,  4],
          [ 6,  2,  3],
          [ 3,  5,  6],
          [ 9,  8, 10]]],


        [[[ 2, 10, 11],
          [ 3,  2,  9],
          [ 7,  7,  2],
          [ 3,  3,  4]]]]])>

In [29]:
tensor *= 10
tensor

<tf.Tensor: shape=(2, 1, 4, 3), dtype=int64, numpy=
array([[[[ 60, 100,  40],
         [ 60,  20,  30],
         [ 30,  50,  60],
         [ 90,  80, 100]]],


       [[[ 20, 100, 110],
         [ 30,  20,  90],
         [ 70,  70,  20],
         [ 30,  30,  40]]]])>

In [30]:
print(tensor)

tf.subtract(tensor, 10)

tf.Tensor(
[[[[ 60 100  40]
   [ 60  20  30]
   [ 30  50  60]
   [ 90  80 100]]]


 [[[ 20 100 110]
   [ 30  20  90]
   [ 70  70  20]
   [ 30  30  40]]]], shape=(2, 1, 4, 3), dtype=int64)


<tf.Tensor: shape=(2, 1, 4, 3), dtype=int64, numpy=
array([[[[ 50,  90,  30],
         [ 50,  10,  20],
         [ 20,  40,  50],
         [ 80,  70,  90]]],


       [[[ 10,  90, 100],
         [ 20,  10,  80],
         [ 60,  60,  10],
         [ 20,  20,  30]]]])>

In [31]:
# a = tf.reshape(tensor, shape=(3,1,2))
# a
# tf.matmul(tensor, a)

In [32]:
tensor.shape

TensorShape([2, 1, 4, 3])

In [33]:
tensor1 = tf.random.uniform((2,3,6), minval=1, maxval=10, dtype=tf.int64)
tf.matmul(tensor, tensor1)

<tf.Tensor: shape=(2, 2, 4, 6), dtype=int64, numpy=
array([[[[ 740,  940,  940, 1500,  780, 1400],
         [ 350,  700,  730,  930,  620,  670],
         [ 650,  790,  670, 1110,  710, 1060],
         [1110, 1590, 1470, 2190, 1420, 1900]],

        [[1140,  200, 1260,  720, 1020, 1700],
         [ 500,  110,  510,  450,  510,  900],
         [ 890,  140,  750,  480,  630, 1170],
         [1540,  270, 1380,  990, 1230, 2240]]],


       [[[1190, 1220,  930, 1770, 1100, 1870],
         [ 740,  970,  760, 1200,  920, 1090],
         [ 490,  790,  870, 1230,  650, 1020],
         [ 430,  590,  530,  810,  530,  720]],

        [[1620,  230, 1310,  730, 1030, 1940],
         [ 920,  140,  570,  480,  540, 1140],
         [ 790,  160,  970,  620,  830, 1350],
         [ 590,  100,  510,  360,  450,  830]]]])>

In [34]:
tensor_A = tf.random.uniform((3,3), minval=1, maxval=8, dtype=tf.int32)
tensor_B = tf.constant([[3,5],
                        [-6,7],
                        [1,8]])

tensor_A

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[5, 1, 1],
       [6, 5, 6],
       [5, 3, 4]], dtype=int32)>

In [35]:
# 3 different methods:

# tf.matmul(tensor_A, tensor_B)
# tf.tensordot(tensor_A, tensor_B, axes=1)
# tensor_A @ tensor_B

In [36]:
tensor_B = tf.cast(tensor_B, dtype=tf.float64)

In [37]:
tf.abs(tensor_A)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[5, 1, 1],
       [6, 5, 6],
       [5, 3, 4]], dtype=int32)>

In [38]:
tf.math.reduce_std(tensor_B)

<tf.Tensor: shape=(), dtype=float64, numpy=4.654746681256314>

In [39]:
tf.math.argmin(tensor_B, axis=1).numpy()

array([0, 0, 0])

In [40]:
tensor_B

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[ 3.,  5.],
       [-6.,  7.],
       [ 1.,  8.]])>

In [41]:
tf.random.set_seed(42)
f = tf.random.uniform([50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [42]:
a = tf.random.uniform([3,4], maxval=20, dtype=tf.int32)
a

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[18,  3, 19, 14],
       [12, 13,  4,  2],
       [ 6,  4,  1,  3]], dtype=int32)>

In [43]:
tf.argmax(a)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([0, 1, 0, 0])>

In [44]:
tf.reduce_max(a).numpy()

19

In [45]:
b = tf.random.uniform([1,1,1,1,50])
b

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764,
           0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ,
           0.6936141 , 0.07321334, 0.93251204, 0.20843053, 0.70105827,
           0.45856392, 0.8596262 , 0.92934334, 0.20291913, 0.76865506,
           0.60016024, 0.27039742, 0.88180614, 0.05365038, 0.42274463,
           0.89037776, 0.7887033 , 0.10165584, 0.19408834, 0.27896714,
           0.39512634, 0.12235212, 0.38412368, 0.9455296 , 0.77594674,
           0.94442344, 0.04296565, 0.4746096 , 0.6548251 , 0.5657116 ,
           0.13858628, 0.3004663 , 0.3311677 , 0.12907016, 0.6435652 ,
           0.45473957, 0.68881893, 0.30203617, 0.49152803, 0.26529062]]]]],
      dtype=float32)>

In [46]:
b_squeezed = tf.squeeze(b)
b_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764,
       0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ,
       0.6936141 , 0.07321334, 0.93251204, 0.20843053, 0.70105827,
       0.45856392, 0.8596262 , 0.92934334, 0.20291913, 0.76865506,
       0.60016024, 0.27039742, 0.88180614, 0.05365038, 0.42274463,
       0.89037776, 0.7887033 , 0.10165584, 0.19408834, 0.27896714,
       0.39512634, 0.12235212, 0.38412368, 0.9455296 , 0.77594674,
       0.94442344, 0.04296565, 0.4746096 , 0.6548251 , 0.5657116 ,
       0.13858628, 0.3004663 , 0.3311677 , 0.12907016, 0.6435652 ,
       0.45473957, 0.68881893, 0.30203617, 0.49152803, 0.26529062],
      dtype=float32)>

#One Hot encoding tensors

In [47]:
some_list = [0,1,6,3,7]
tf.one_hot(some_list, depth=8)

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

In [48]:
c = tf.range(1,11)
c

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>

In [49]:
tf.sqrt(tf.cast(c, dtype=tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       , 3.1622777], dtype=float32)>

In [50]:
d = tf.math.log(tf.cast(c, dtype=tf.float32))

In [51]:
tf.math.ceil(d)

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 1., 2., 2., 2., 2., 2., 3., 3., 3.], dtype=float32)>

In [52]:
tf.pow(d, 3)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([ 0.        ,  0.33302468,  1.325969  ,  2.6641972 ,  4.1689124 ,
        5.752269  ,  7.3683176 ,  8.991665  , 10.607751  , 12.208073  ],
      dtype=float32)>

In [53]:
tf.math.negative(tensor_B)

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[-3., -5.],
       [ 6., -7.],
       [-1., -8.]])>

In [54]:
a = tf.constant(np.array([1,2,3,4]))
b = tf.constant([1,2,3,4])
a.dtype, b.dtype

(tf.int64, tf.int32)

In [55]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [56]:
!nvidia-smi

Sat Jul 22 18:14:53 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P0    26W /  70W |    389MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------