<a href="https://colab.research.google.com/github/nika-va/practice/blob/main/tensorflow_fundamentas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* Introduction to tensors (creating tensors)
* Getting information from tensors (tensor attributes)
* Manipulating tensors (tensor operations)
* Tensors and NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow
* Exercises to try

In [2]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [3]:
a = tf.constant([[2,5,20]], dtype=tf.float32)

In [4]:
a.ndim

2

In [5]:
a

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 2.,  5., 20.]], dtype=float32)>

In [6]:
# scalar 0
# vector 1
# matrix 2
# tensor n+

In [7]:
# tensors with tf.Variable
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [8]:
changeable_tensor[0].assign(2)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([2, 7], dtype=int32)>

### Random Tensors

In [10]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal([2,3])
random_2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [11]:
not_shuffled = tf.random.Generator.from_seed(7).normal([3,2])
not_shuffled


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [12]:
tf.random.set_seed(32)
tf.random.shuffle(not_shuffled, seed=3)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.8757901 , -0.08857018],
       [-1.3240396 ,  0.28785667],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [13]:

# Set the random seed
tf.random.set_seed(42)

# Generate some random numbers
a = tf.random.normal([1])
b = tf.random.normal([1])

# Check that the results are the same every time
print(a)
print(b)

tf.Tensor([0.3274685], shape=(1,), dtype=float32)
tf.Tensor([0.08422458], shape=(1,), dtype=float32)


In [14]:
tf.random.set_seed(42)
# Generate some random numbers with a specific seed
a = tf.random.normal([1])

# Check that the results are the same every time
print(a)


tf.Tensor([0.3274685], shape=(1,), dtype=float32)


In [15]:

b = tf.random.normal([1])
print(b)

tf.Tensor([0.08422458], shape=(1,), dtype=float32)


In [23]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal([4,5])
print(random_1)
tf.random.shuffle(random_1)

tf.Tensor(
[[-0.7565803  -0.06854702  0.07595026 -1.2573844  -0.23193763]
 [-1.8107855   0.09988727 -0.50998646 -0.7535805  -0.57166284]
 [ 0.1480774  -0.23362993 -0.3522796   0.40621263 -1.0523509 ]
 [ 1.2054597   1.6874489  -0.4462975  -2.3410842   0.99009085]], shape=(4, 5), dtype=float32)


<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[ 1.2054597 ,  1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085],
       [ 0.1480774 , -0.23362993, -0.3522796 ,  0.40621263, -1.0523509 ],
       [-1.8107855 ,  0.09988727, -0.50998646, -0.7535805 , -0.57166284],
       [-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193763]],
      dtype=float32)>

In [25]:
tf.ones([10,7])
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [27]:
import numpy as np
np.ones([10,7])

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [30]:
numpy = np.arange(1,25)
numpy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [31]:
tf.constant(numpy, shape = (2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [34]:
a = np.arange(1,61, dtype=np.int32)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60], dtype=int32)

In [35]:
tf.constant(a, shape=(5,6,2))

<tf.Tensor: shape=(5, 6, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18],
        [19, 20],
        [21, 22],
        [23, 24]],

       [[25, 26],
        [27, 28],
        [29, 30],
        [31, 32],
        [33, 34],
        [35, 36]],

       [[37, 38],
        [39, 40],
        [41, 42],
        [43, 44],
        [45, 46],
        [47, 48]],

       [[49, 50],
        [51, 52],
        [53, 54],
        [55, 56],
        [57, 58],
        [59, 60]]], dtype=int32)>