<a href="https://colab.research.google.com/github/nika-va/practice/blob/main/tensorflow_fundamentas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* Introduction to tensors (creating tensors)
* Getting information from tensors (tensor attributes)
* Manipulating tensors (tensor operations)
* Tensors and NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow
* Exercises to try

In [1]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [2]:
a = tf.constant([[2,5,20]], dtype=tf.float32)

In [3]:
a.ndim

2

In [4]:
a

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 2.,  5., 20.]], dtype=float32)>

In [5]:
# scalar 0
# vector 1
# matrix 2
# tensor n+

In [6]:
# tensors with tf.Variable
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [7]:
changeable_tensor[0].assign(2)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([2, 7], dtype=int32)>

### Random Tensors

In [8]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal([2,3])
random_2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [9]:
not_shuffled = tf.random.Generator.from_seed(7).normal([3,2])
not_shuffled


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [10]:
tf.random.set_seed(32)
tf.random.shuffle(not_shuffled, seed=3)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.8757901 , -0.08857018],
       [-1.3240396 ,  0.28785667],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [11]:

# Set the random seed
tf.random.set_seed(42)

# Generate some random numbers
a = tf.random.normal([1])
b = tf.random.normal([1])

# Check that the results are the same every time
print(a)
print(b)

tf.Tensor([0.3274685], shape=(1,), dtype=float32)
tf.Tensor([0.08422458], shape=(1,), dtype=float32)


In [12]:
tf.random.set_seed(42)
# Generate some random numbers with a specific seed
a = tf.random.normal([1])

# Check that the results are the same every time
print(a)


tf.Tensor([0.3274685], shape=(1,), dtype=float32)


In [13]:

b = tf.random.normal([1])
print(b)

tf.Tensor([0.08422458], shape=(1,), dtype=float32)


In [14]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal([4,5])
print(random_1)
tf.random.shuffle(random_1)

tf.Tensor(
[[-0.7565803  -0.06854702  0.07595026 -1.2573844  -0.23193763]
 [-1.8107855   0.09988727 -0.50998646 -0.7535805  -0.57166284]
 [ 0.1480774  -0.23362993 -0.3522796   0.40621263 -1.0523509 ]
 [ 1.2054597   1.6874489  -0.4462975  -2.3410842   0.99009085]], shape=(4, 5), dtype=float32)


<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193763],
       [ 1.2054597 ,  1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085],
       [-1.8107855 ,  0.09988727, -0.50998646, -0.7535805 , -0.57166284],
       [ 0.1480774 , -0.23362993, -0.3522796 ,  0.40621263, -1.0523509 ]],
      dtype=float32)>

In [15]:
tf.ones([10,7])
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [16]:
import numpy as np
np.ones([10,7])

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [17]:
numpy = np.arange(1,25)
numpy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [18]:
tf.constant(numpy, shape = (2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [19]:
a = np.arange(1,61, dtype=np.int32)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60], dtype=int32)

In [20]:
b = tf.constant(a, shape=(5,6,2))
b

<tf.Tensor: shape=(5, 6, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18],
        [19, 20],
        [21, 22],
        [23, 24]],

       [[25, 26],
        [27, 28],
        [29, 30],
        [31, 32],
        [33, 34],
        [35, 36]],

       [[37, 38],
        [39, 40],
        [41, 42],
        [43, 44],
        [45, 46],
        [47, 48]],

       [[49, 50],
        [51, 52],
        [53, 54],
        [55, 56],
        [57, 58],
        [59, 60]]], dtype=int32)>

In [21]:
a.shape


(60,)

In [22]:
b[0, :2]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [23]:
tensor = tf.random.uniform((2,4,3), minval=2, maxval=12, dtype=tf.int64)
tensor

<tf.Tensor: shape=(2, 4, 3), dtype=int64, numpy=
array([[[ 6, 10,  4],
        [ 6,  2,  3],
        [ 3,  5,  6],
        [ 9,  8, 10]],

       [[ 2, 10, 11],
        [ 3,  2,  9],
        [ 7,  7,  2],
        [ 3,  3,  4]]])>

In [24]:
tensor[:, -1]

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[ 9,  8, 10],
       [ 3,  3,  4]])>

In [25]:
# Adding extra dimention to our rank 2 tensor
tensor = tensor[:, tf.newaxis, :]
tensor

<tf.Tensor: shape=(2, 1, 4, 3), dtype=int64, numpy=
array([[[[ 6, 10,  4],
         [ 6,  2,  3],
         [ 3,  5,  6],
         [ 9,  8, 10]]],


       [[[ 2, 10, 11],
         [ 3,  2,  9],
         [ 7,  7,  2],
         [ 3,  3,  4]]]])>

In [26]:
# a = tf.expand_dims(tensor, axis=-1)
# a = tf.tile(a, multiples=[2,2,2,2])
# a.shape

In [27]:
tf.expand_dims(tensor, axis=0)

<tf.Tensor: shape=(1, 2, 1, 4, 3), dtype=int64, numpy=
array([[[[[ 6, 10,  4],
          [ 6,  2,  3],
          [ 3,  5,  6],
          [ 9,  8, 10]]],


        [[[ 2, 10, 11],
          [ 3,  2,  9],
          [ 7,  7,  2],
          [ 3,  3,  4]]]]])>

In [28]:
tensor *= 10
tensor

<tf.Tensor: shape=(2, 1, 4, 3), dtype=int64, numpy=
array([[[[ 60, 100,  40],
         [ 60,  20,  30],
         [ 30,  50,  60],
         [ 90,  80, 100]]],


       [[[ 20, 100, 110],
         [ 30,  20,  90],
         [ 70,  70,  20],
         [ 30,  30,  40]]]])>

In [29]:
print(tensor)

tf.subtract(tensor, 10)

tf.Tensor(
[[[[ 60 100  40]
   [ 60  20  30]
   [ 30  50  60]
   [ 90  80 100]]]


 [[[ 20 100 110]
   [ 30  20  90]
   [ 70  70  20]
   [ 30  30  40]]]], shape=(2, 1, 4, 3), dtype=int64)


<tf.Tensor: shape=(2, 1, 4, 3), dtype=int64, numpy=
array([[[[ 50,  90,  30],
         [ 50,  10,  20],
         [ 20,  40,  50],
         [ 80,  70,  90]]],


       [[[ 10,  90, 100],
         [ 20,  10,  80],
         [ 60,  60,  10],
         [ 20,  20,  30]]]])>

In [30]:
# a = tf.reshape(tensor, shape=(3,1,2))
# a
# tf.matmul(tensor, a)

In [31]:
tensor.shape

TensorShape([2, 1, 4, 3])

In [32]:
tensor1 = tf.random.uniform((2,3,6), minval=1, maxval=10, dtype=tf.int64)
tf.matmul(tensor, tensor1)

<tf.Tensor: shape=(2, 2, 4, 6), dtype=int64, numpy=
array([[[[ 740,  940,  940, 1500,  780, 1400],
         [ 350,  700,  730,  930,  620,  670],
         [ 650,  790,  670, 1110,  710, 1060],
         [1110, 1590, 1470, 2190, 1420, 1900]],

        [[1140,  200, 1260,  720, 1020, 1700],
         [ 500,  110,  510,  450,  510,  900],
         [ 890,  140,  750,  480,  630, 1170],
         [1540,  270, 1380,  990, 1230, 2240]]],


       [[[1190, 1220,  930, 1770, 1100, 1870],
         [ 740,  970,  760, 1200,  920, 1090],
         [ 490,  790,  870, 1230,  650, 1020],
         [ 430,  590,  530,  810,  530,  720]],

        [[1620,  230, 1310,  730, 1030, 1940],
         [ 920,  140,  570,  480,  540, 1140],
         [ 790,  160,  970,  620,  830, 1350],
         [ 590,  100,  510,  360,  450,  830]]]])>

In [33]:
tensor_A = tf.random.uniform((3,3), minval=1, maxval=8, dtype=tf.int32)
tensor_B = tf.constant([[3,5],
                        [-6,7],
                        [1,8]])

tensor_A

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[5, 1, 1],
       [6, 5, 6],
       [5, 3, 4]], dtype=int32)>

In [34]:
# 3 different methods:

# tf.matmul(tensor_A, tensor_B)
# tf.tensordot(tensor_A, tensor_B, axes=1)
# tensor_A @ tensor_B

In [35]:
tensor_B = tf.cast(tensor_B, dtype=tf.float64)

In [36]:
tf.abs(tensor_A)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[5, 1, 1],
       [6, 5, 6],
       [5, 3, 4]], dtype=int32)>

In [37]:
tf.math.reduce_std(tensor_B)

<tf.Tensor: shape=(), dtype=float64, numpy=4.654746681256314>

In [44]:
tf.math.argmin(tensor_B, axis=1).numpy()

array([0, 0, 0])

In [42]:
tensor_B

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[ 3.,  5.],
       [-6.,  7.],
       [ 1.,  8.]])>

In [46]:
tf.random.set_seed(42)
f = tf.random.uniform([50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [58]:
a = tf.random.uniform([3,4], maxval=20, dtype=tf.int32)
a

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 9,  7,  2,  9],
       [ 2,  2, 18, 13],
       [ 0,  1, 18, 19]], dtype=int32)>

In [59]:
tf.argmax(a)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([0, 0, 1, 2])>

In [61]:
tf.reduce_max(a).numpy()

19

In [65]:
b = tf.random.uniform([1,1,1,1,50])
b

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[1.27802730e-01, 8.62301230e-01, 4.15632963e-01,
           1.00286722e-01, 6.07836485e-01, 7.90521741e-01,
           6.06833696e-02, 8.56746435e-01, 7.20012665e-01,
           6.80043340e-01, 3.18007350e-01, 9.15518522e-01,
           9.83233213e-01, 9.49099660e-01, 9.27690983e-01,
           4.26432252e-01, 1.65649414e-01, 5.96877337e-02,
           1.01531982e-01, 3.48368764e-01, 1.06096268e-05,
           5.53984642e-01, 1.04559660e-02, 1.70157075e-01,
           5.35020947e-01, 3.53641510e-02, 5.11248112e-02,
           3.47512603e-01, 4.17755604e-01, 4.66669559e-01,
           9.22843099e-01, 6.48598909e-01, 3.84631276e-01,
           7.53028631e-01, 9.17651892e-01, 5.70779085e-01,
           9.69477892e-02, 4.58525062e-01, 2.72809863e-01,
           7.18811393e-01, 6.84959650e-01, 9.46360826e-01,
           6.96492195e-02, 1.22516274e-01, 5.67929626e-01,
           6.14467025e-01, 2.55180240e-01, 7.69669652e-01

In [67]:
b_squeezed = tf.squeeze(b)
b_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([1.27802730e-01, 8.62301230e-01, 4.15632963e-01, 1.00286722e-01,
       6.07836485e-01, 7.90521741e-01, 6.06833696e-02, 8.56746435e-01,
       7.20012665e-01, 6.80043340e-01, 3.18007350e-01, 9.15518522e-01,
       9.83233213e-01, 9.49099660e-01, 9.27690983e-01, 4.26432252e-01,
       1.65649414e-01, 5.96877337e-02, 1.01531982e-01, 3.48368764e-01,
       1.06096268e-05, 5.53984642e-01, 1.04559660e-02, 1.70157075e-01,
       5.35020947e-01, 3.53641510e-02, 5.11248112e-02, 3.47512603e-01,
       4.17755604e-01, 4.66669559e-01, 9.22843099e-01, 6.48598909e-01,
       3.84631276e-01, 7.53028631e-01, 9.17651892e-01, 5.70779085e-01,
       9.69477892e-02, 4.58525062e-01, 2.72809863e-01, 7.18811393e-01,
       6.84959650e-01, 9.46360826e-01, 6.96492195e-02, 1.22516274e-01,
       5.67929626e-01, 6.14467025e-01, 2.55180240e-01, 7.69669652e-01,
       3.94763947e-01, 6.69542074e-01], dtype=float32)>

#One Hot encoding tensors

In [77]:
some_list = [0,1,6,3,7]
tf.one_hot(some_list, depth=8)

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>