<a href="https://colab.research.google.com/github/nika-va/practice/blob/main/tensorflow_fundamentas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* Introduction to tensors (creating tensors)
* Getting information from tensors (tensor attributes)
* Manipulating tensors (tensor operations)
* Tensors and NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow
* Exercises to try

In [1]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [2]:
a = tf.constant([[2,5,20]], dtype=tf.float32)

In [3]:
a.ndim

2

In [4]:
a

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 2.,  5., 20.]], dtype=float32)>

In [5]:
# scalar 0
# vector 1
# matrix 2
# tensor n+

In [6]:
# tensors with tf.Variable
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [12]:
changeable_tensor[0].assign(2)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([2, 7], dtype=int32)>

### Random Tensors

In [19]:
# random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

AttributeError: ignored

In [46]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal([2,3])
random_2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [52]:
not_shuffled = tf.random.Generator.from_seed(7).normal([3,2])
not_shuffled


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [62]:
tf.random.set_seed(32)
tf.random.shuffle(not_shuffled, seed=3)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.8757901 , -0.08857018],
       [-1.3240396 ,  0.28785667],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [75]:
a = tf.random.normal([1], seed=42)
b = tf.random.normal([1], seed=42)

# Check that the results are the same every time
print(a)
print(b)

tf.Tensor([1.0530839], shape=(1,), dtype=float32)
tf.Tensor([-0.39724815], shape=(1,), dtype=float32)
